version: "3.8"  # 3.9 ou 3.8, tanto faz

services:
  rl-trainer:
    build: .
    container_name: rl_trainer_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - .:/workspace/app
      - ./src/logs:/workspace/app/logs
      - ./src/test_results:/workspace/app/test_results
    command: python src/train.py
